
# -------------------------------------------------------------------------------------------------------------------
# This code extracts individual cluster information from the clusters generated by Markov Cluster Algorithm.

# Input - The clusters genertaed by MCL stored in 'PLG_Clustering/MCL_Clusters/out.Shared_Edges.txt.I20'. 
# Output - The individual clusters saved as .txt files in 'GO/Individual_Clusters/'.
# -------------------------------------------------------------------------------------------------------------------

import numpy as np
import pickle
import copy
import random
import os



def main():
	count = 1
	output_dir = '../Individual_Clusters1/' # Output Folder
	if not os.path.isdir(output_dir):
		cmd_str = 'mkdir ' + output_dir
		os.system(cmd_str)

	with open("../../PLG_Clustering/MCL_Clusters/out.Shared_Edges.txt.I20") as fp: # Input File - MCL output file
		for line in fp:
			word = line.split('\t')
			output_file = output_dir + '/' + str(count) + '.txt'
			fp_write = open(output_file,'w')	
			for wd in word:				
				fp_write.write(wd + '\n')
			fp_write.close()

			count += 1

		
#----------------------------------------------------------------
if __name__ == '__main__':
	main()
